/**********************************************************
* BreakingNewsDTO.java : 
*
* Created by Ankur
* Last modified Date: 18 Apr .08 by Pratik
* Revision: 0.1
* Version : 0.0.8
* Copyright (c) 2008 - 2008 Askdigi, All rights reserved.
**********************************************************/
package com.g4g.dto;

/**
 * BreakingNewsDTO is the DTO class for Thread table in database for blog/forum.
 * Thread table contains titile, firstpostid etc. attributes. Thread table contains
 * information about forum/blog threads generated by different users.
 * 
 * @author Ankur
 * @see BaseDTO
 * @hibernate.mapping BreakingNewsDTO.hbm.xml
 */

public class BreakingNewsDTO extends BaseDTO {

	// Fields

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The title. */
	private String title;

	/** The firstpostid. */
	private Integer firstpostid;

	/** The lastpostid. */
	private Integer lastpostid;

	/** The lastpost. */
	private Integer lastpost;

	/** The forumid. */
	private Short forumid;

	/** The pollid. */
	private Integer pollid;

	/** The open. */
	private Short open;

	/** The replycount. */
	private Integer replycount;

	/** The hiddencount. */
	private Integer hiddencount;

	/** The deletedcount. */
	private Integer deletedcount;

	/** The postusername. */
	private String postusername;

	/** The postuserid. */
	private Integer postuserid;

	/** The lastposter. */
	private String lastposter;

	/** The dateline. */
	private Integer dateline;

	/** The views. */
	private Integer views;

	/** The iconid. */
	private Short iconid;

	/** The notes. */
	private String notes;

	/** The visible. */
	private Short visible;

	/** The sticky. */
	private Short sticky;

	/** The votenum. */
	private Short votenum;

	/** The votetotal. */
	private Short votetotal;

	/** The attach. */
	private Short attach;

	/** The similar. */
	private String similar;

	// Constructors

	/**
	 * default constructor.
	 */
	public BreakingNewsDTO() {
	}

	// Property accessors

	/**
	 * Gets the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 * 
	 * @param title
	 *            the title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the firstpostid.
	 * 
	 * @return firstpostid
	 */
	public Integer getFirstpostid() {
		return this.firstpostid;
	}

	/**
	 * Sets the firstpostid.
	 * 
	 * @param firstpostid
	 *            the firstpostid
	 */
	public void setFirstpostid(Integer firstpostid) {
		this.firstpostid = firstpostid;
	}

	/**
	 * Gets the lastpostid.
	 * 
	 * @return lastpostid
	 */
	public Integer getLastpostid() {
		return this.lastpostid;
	}

	/**
	 * Sets the lastpostid.
	 * 
	 * @param lastpostid
	 *            the lastpostid
	 */
	public void setLastpostid(Integer lastpostid) {
		this.lastpostid = lastpostid;
	}

	/**
	 * Gets the lastpost.
	 * 
	 * @return lastpost
	 */
	public Integer getLastpost() {
		return this.lastpost;
	}

	/**
	 * Sets the lastpost.
	 * 
	 * @param lastpost
	 *            the lastpost
	 */
	public void setLastpost(Integer lastpost) {
		this.lastpost = lastpost;
	}

	/**
	 * Gets the forumid.
	 * 
	 * @return forumid
	 */
	public Short getForumid() {
		return this.forumid;
	}

	/**
	 * Sets the forumid.
	 * 
	 * @param forumid
	 *            the forumid
	 */
	public void setForumid(Short forumid) {
		this.forumid = forumid;
	}

	/**
	 * Gets the pollid.
	 * 
	 * @return pollid
	 */
	public Integer getPollid() {
		return this.pollid;
	}

	/**
	 * Sets the pollid.
	 * 
	 * @param pollid
	 *            the pollid
	 */
	public void setPollid(Integer pollid) {
		this.pollid = pollid;
	}

	/**
	 * Gets the open.
	 * 
	 * @return open
	 */
	public Short getOpen() {
		return this.open;
	}

	/**
	 * Sets the open.
	 * 
	 * @param open
	 *            the open
	 */
	public void setOpen(Short open) {
		this.open = open;
	}

	/**
	 * Gets the replycount.
	 * 
	 * @return replycount
	 */
	public Integer getReplycount() {
		return this.replycount;
	}

	/**
	 * Sets the replycount.
	 * 
	 * @param replycount
	 *            the replycount
	 */
	public void setReplycount(Integer replycount) {
		this.replycount = replycount;
	}

	/**
	 * Gets the hiddencount.
	 * 
	 * @return hiddencount
	 */
	public Integer getHiddencount() {
		return this.hiddencount;
	}

	/**
	 * Sets the hiddencount.
	 * 
	 * @param hiddencount
	 *            the hiddencount
	 */
	public void setHiddencount(Integer hiddencount) {
		this.hiddencount = hiddencount;
	}

	/**
	 * Gets the deletedcount.
	 * 
	 * @return deletedcount
	 */
	public Integer getDeletedcount() {
		return this.deletedcount;
	}

	/**
	 * Sets the deletedcount.
	 * 
	 * @param deletedcount
	 *            the deletedcount
	 */
	public void setDeletedcount(Integer deletedcount) {
		this.deletedcount = deletedcount;
	}

	/**
	 * Gets the postusername.
	 * 
	 * @return postusername
	 */
	public String getPostusername() {
		return this.postusername;
	}

	/**
	 * Sets the postusername.
	 * 
	 * @param postusername
	 *            the postusername
	 */
	public void setPostusername(String postusername) {
		this.postusername = postusername;
	}

	/**
	 * Gets the postuserid.
	 * 
	 * @return postuserid
	 */
	public Integer getPostuserid() {
		return this.postuserid;
	}

	/**
	 * Sets the postuserid.
	 * 
	 * @param postuserid
	 *            the postuserid
	 */
	public void setPostuserid(Integer postuserid) {
		this.postuserid = postuserid;
	}

	/**
	 * Gets the lastposter.
	 * 
	 * @return lastposter
	 */
	public String getLastposter() {
		return this.lastposter;
	}

	/**
	 * Sets the lastposter.
	 * 
	 * @param lastposter
	 *            the lastposter
	 */
	public void setLastposter(String lastposter) {
		this.lastposter = lastposter;
	}

	/**
	 * Gets the dateline.
	 * 
	 * @return dateline
	 */
	public Integer getDateline() {
		return this.dateline;
	}

	/**
	 * Sets the dateline.
	 * 
	 * @param dateline
	 *            the dateline
	 */
	public void setDateline(Integer dateline) {
		this.dateline = dateline;
	}

	/**
	 * Gets the views.
	 * 
	 * @return views
	 */
	public Integer getViews() {
		return this.views;
	}

	/**
	 * Sets the views.
	 * 
	 * @param views
	 *            the views
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * Gets the iconid.
	 * 
	 * @return iconid
	 */
	public Short getIconid() {
		return this.iconid;
	}

	/**
	 * Sets the iconid.
	 * 
	 * @param iconid
	 *            the iconid
	 */
	public void setIconid(Short iconid) {
		this.iconid = iconid;
	}

	/**
	 * Gets the notes.
	 * 
	 * @return notes
	 */
	public String getNotes() {
		return this.notes;
	}

	/**
	 * Sets the notes.
	 * 
	 * @param notes
	 *            the notes
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Gets the visible.
	 * 
	 * @return visible
	 */
	public Short getVisible() {
		return this.visible;
	}

	/**
	 * Sets the visible.
	 * 
	 * @param visible
	 *            the visible
	 */
	public void setVisible(Short visible) {
		this.visible = visible;
	}

	/**
	 * Gets the sticky.
	 * 
	 * @return sticky
	 */
	public Short getSticky() {
		return this.sticky;
	}

	/**
	 * Sets the sticky.
	 * 
	 * @param sticky
	 *            the sticky
	 */
	public void setSticky(Short sticky) {
		this.sticky = sticky;
	}

	/**
	 * Gets the votenum.
	 * 
	 * @return votenum
	 */
	public Short getVotenum() {
		return this.votenum;
	}

	/**
	 * Sets the votenum.
	 * 
	 * @param votenum
	 *            the votenum
	 */
	public void setVotenum(Short votenum) {
		this.votenum = votenum;
	}

	/**
	 * Gets the votetotal.
	 * 
	 * @return votetotal
	 */
	public Short getVotetotal() {
		return this.votetotal;
	}

	/**
	 * Sets the votetotal.
	 * 
	 * @param votetotal
	 *            the votetotal
	 */
	public void setVotetotal(Short votetotal) {
		this.votetotal = votetotal;
	}

	/**
	 * Gets the attach.
	 * 
	 * @return attach
	 */
	public Short getAttach() {
		return this.attach;
	}

	/**
	 * Sets the attach.
	 * 
	 * @param attach
	 *            the attach
	 */
	public void setAttach(Short attach) {
		this.attach = attach;
	}

	/**
	 * Gets the similar.
	 * 
	 * @return similar
	 */
	public String getSimilar() {
		return this.similar;
	}

	/**
	 * Sets the similar.
	 * 
	 * @param similar
	 *            the similar
	 */
	public void setSimilar(String similar) {
		this.similar = similar;
	}

}