package com.g4g.dto;

// Generated May 13, 2008 7:17:30 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Twoplayermatch generated by hbm2java
 */
public class TwoplayermatchDTO extends BaseDTO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TwoplayertournamentDTO twoplayertournament;
	private PlayerDTO playertwoid;
	private TwoplayermatchDTO nextmatch;
	private PlayerDTO playeroneid;
	private Integer level;
	private Date playeroneaccepteddate;
	private Date playertwoaccepteddate;
	private PlayerDTO winnerid;
	private Double payoutamount;
	private Date scheduledstartdate;
	private Date completeddate;
	private Integer gamecompleted;
	private String matchstatus;
	private String resultbody;
	private Date enddate;
	private transient Set<FeedbackreputationDTO> feedbackreputations = new HashSet<FeedbackreputationDTO>(
			0);

	/**
	 * 
	 */
	public TwoplayermatchDTO() {
	}

	/**
	 * @param matchid
	 */
	public TwoplayermatchDTO(int matchid) {
		this.id = matchid;
	}

	/**
	 * @param level
	 * @param payoutamount
	 * @param scheduledstartdate
	 * @param enddate
	 * @param gamecompleted
	 * @param matchstatus
	 */
	public TwoplayermatchDTO(Integer level, Double payoutamount,
			Date scheduledstartdate, Date enddate, Integer gamecompleted,
			String matchstatus) {
		super();
		this.level = level;
		this.payoutamount = payoutamount;
		this.scheduledstartdate = scheduledstartdate;
		this.enddate = enddate;
		this.gamecompleted = gamecompleted;
		this.matchstatus = matchstatus;

	}

	/**
	 * @param matchid
	 * @param twoplayertournament
	 * @param playerByPlayertwoid
	 * @param nextmatch
	 * @param playerByPlayeroneid
	 * @param level
	 * @param playeroneaccepteddate
	 * @param playertwoaccepteddate
	 * @param winnerid
	 * @param payoutamount
	 * @param scheduledstartdate
	 * @param completeddate
	 * @param gamecompleted
	 * @param matchstatus
	 * @param resultbody
	 * @param enddate
	 * @param feedbackreputations
	 */
	public TwoplayermatchDTO(int matchid,
			TwoplayertournamentDTO twoplayertournament,
			PlayerDTO playerByPlayertwoid, TwoplayermatchDTO nextmatch,
			PlayerDTO playerByPlayeroneid, Integer level,
			Date playeroneaccepteddate, Date playertwoaccepteddate,
			PlayerDTO winnerid, Double payoutamount, Date scheduledstartdate,
			Date completeddate, Integer gamecompleted, String matchstatus,
			String resultbody, Date enddate,
			Set<FeedbackreputationDTO> feedbackreputations) {
		this.id = matchid;
		this.twoplayertournament = twoplayertournament;
		this.playertwoid = playerByPlayertwoid;
		this.nextmatch = nextmatch;
		this.playeroneid = playerByPlayeroneid;
		this.level = level;
		this.playeroneaccepteddate = playeroneaccepteddate;
		this.playertwoaccepteddate = playertwoaccepteddate;
		this.winnerid = winnerid;
		this.payoutamount = payoutamount;
		this.scheduledstartdate = scheduledstartdate;
		this.completeddate = completeddate;
		this.gamecompleted = gamecompleted;
		this.matchstatus = matchstatus;
		this.resultbody = resultbody;
		this.enddate = enddate;
		this.feedbackreputations = feedbackreputations;
	}

	/**
	 * @return the twoplayertournament
	 */
	public TwoplayertournamentDTO getTwoplayertournament() {
		return this.twoplayertournament;
	}

	/**
	 * @param twoplayertournament
	 *            the twoplayertournament to set
	 */
	public void setTwoplayertournament(
			TwoplayertournamentDTO twoplayertournament) {
		this.twoplayertournament = twoplayertournament;
	}

	/**
	 * @return the playertwoid
	 */
	public PlayerDTO getPlayertwoid() {
		return this.playertwoid;
	}

	/**
	 * @param playertwoid
	 *            the playertwoid to set
	 */
	public void setPlayertwoid(PlayerDTO playertwoid) {
		this.playertwoid = playertwoid;
	}

	/**
	 * @return the nextmatch
	 */
	public TwoplayermatchDTO getNextmatch() {
		return this.nextmatch;
	}

	/**
	 * @param nextmatch
	 *            the nextmatch to set
	 */
	public void setNextmatch(TwoplayermatchDTO nextmatch) {
		this.nextmatch = nextmatch;
	}

	/**
	 * @return the playeroneid
	 */
	public PlayerDTO getPlayeroneid() {
		return this.playeroneid;
	}

	/**
	 * @param playeroneid
	 *            the playeroneid to set
	 */
	public void setPlayeroneid(PlayerDTO playeroneid) {
		this.playeroneid = playeroneid;
	}

	/**
	 * @return the level
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * @param level
	 *            the level to set
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * @return the playeroneaccepteddate
	 */
	public Date getPlayeroneaccepteddate() {
		return this.playeroneaccepteddate;
	}

	/**
	 * @param playeroneaccepteddate
	 *            the playeroneaccepteddate to set
	 */
	public void setPlayeroneaccepteddate(Date playeroneaccepteddate) {
		this.playeroneaccepteddate = playeroneaccepteddate;
	}

	/**
	 * @return the playertwoaccepteddate
	 */
	public Date getPlayertwoaccepteddate() {
		return this.playertwoaccepteddate;
	}

	/**
	 * @param playertwoaccepteddate
	 *            the playertwoaccepteddate to set
	 */
	public void setPlayertwoaccepteddate(Date playertwoaccepteddate) {
		this.playertwoaccepteddate = playertwoaccepteddate;
	}

	/**
	 * @return the winnerid
	 */
	public PlayerDTO getWinnerid() {
		return this.winnerid;
	}

	/**
	 * @param winnerid
	 *            the winnerid to set
	 */
	public void setWinnerid(PlayerDTO winnerid) {
		this.winnerid = winnerid;
	}

	/**
	 * @return the payoutamount
	 */
	public Double getPayoutamount() {
		return this.payoutamount;
	}

	/**
	 * @param payoutamount
	 *            the payoutamount to set
	 */
	public void setPayoutamount(Double payoutamount) {
		this.payoutamount = payoutamount;
	}

	/**
	 * @return the scheduledstartdate
	 */
	public Date getScheduledstartdate() {
		return this.scheduledstartdate;
	}

	/**
	 * @param scheduledstartdate
	 *            the scheduledstartdate to set
	 */
	public void setScheduledstartdate(Date scheduledstartdate) {
		this.scheduledstartdate = scheduledstartdate;
	}

	/**
	 * @return the completeddate
	 */
	public Date getCompleteddate() {
		return this.completeddate;
	}

	/**
	 * @param completeddate
	 *            the completeddate to set
	 */
	public void setCompleteddate(Date completeddate) {
		this.completeddate = completeddate;
	}

	/**
	 * @return the gamecompleted
	 */
	public Integer getGamecompleted() {
		return this.gamecompleted;
	}

	/**
	 * @param gamecompleted
	 *            the gamecompleted to set
	 */
	public void setGamecompleted(Integer gamecompleted) {
		this.gamecompleted = gamecompleted;
	}

	/**
	 * @return the matchstatus
	 */
	public String getMatchstatus() {
		return this.matchstatus;
	}

	/**
	 * @param matchstatus
	 *            the matchstatus to set
	 */
	public void setMatchstatus(String matchstatus) {
		this.matchstatus = matchstatus;
	}

	/**
	 * @return the resultbody
	 */
	public String getResultbody() {
		return this.resultbody;
	}

	/**
	 * @param resultbody
	 *            the resultbody to set
	 */
	public void setResultbody(String resultbody) {
		this.resultbody = resultbody;
	}

	/**
	 * @return the enddate
	 */
	public Date getEnddate() {
		return this.enddate;
	}

	/**
	 * @param enddate
	 *            the enddate to set
	 */
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	/**
	 * @return the feedbackreputations
	 */
	public Set<FeedbackreputationDTO> getFeedbackreputations() {
		return this.feedbackreputations;
	}

	/**
	 * @param feedbackreputations
	 *            the feedbackreputations to set
	 */
	public void setFeedbackreputations(
			Set<FeedbackreputationDTO> feedbackreputations) {
		this.feedbackreputations = feedbackreputations;
	}

}
